name: Tests Pipeline

on: [push, pull_request]

jobs:
  node-react-boilerplate:
    name: pipeline (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 'secret'
          MYSQL_DATABASE: 'boilerplate'
          MYSQL_USER: 'user'
          MYSQL_PASSWORD: 'secret'
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      matrix:
        node-version: ['20.x']
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - uses: mskelton/setup-yarn@v1
      with:
        flags: --immutable-cache
    - name: Setup Env Variables
      run: |
          cp .env.testing .env
          sed -i "s/3306/${{ job.services.mysql.ports['3306'] }}/g" config.json
    - name: Install dependencies
      run: yarn install --silent
    - name: Run database migrations
      run: NODE_ENV=test yarn migrate
    - name: Run database seeders
      run: NODE_ENV=test yarn seed
    - name: Run server in background
      run: yarn start &
    - name: Run tests
      run: yarn run test
